# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [4]:
pip install mdutils

Note: you may need to restart the kernel to use updated packages.


In [40]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [41]:
import numpy as np

answer(1)

import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆)

In [13]:
print(np.__version__)

1.17.2


#### 3. Create a null vector of size 10 (★☆☆)

In [20]:
a = np.zeros((0, 10))
a

answer(3)

Z = np.zeros(10)
print(Z)


#### 4. How to find the memory size of any array (★☆☆)

In [39]:
hint(4)

a = np.array([1, 2])
a.size
print('%d bytes' %(a.size * a.itemsize))

answer(4)

hint: size, itemsize
16 bytes
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [47]:
hint(5)

#np.info(np.sum)#sum아님!!
np.info(np.add)

answer(5)

hint: np.info
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
 

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [55]:
vector = np.zeros(10)
vector[4] = 1

vector

#answer(6)

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [59]:
vector = np.arange(10, 50)
vector

#answer(7)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [62]:
flip_vector = np.flip(vector) # flip_vector = vector[::-1]
flip_vector

answer(8)

Z = np.arange(50)
Z = Z[::-1]
print(Z)


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [66]:
matrix = np.arange(9).reshape(3, 3)
matrix

answer(9)
 

nz = np.nonzero([1,2,0,0,4,0])
print(nz)
(array([0, 1, 4]),)


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [71]:
list = np.array([1, 2, 0, 0, 4, 0])
print(np.nonzero(list))

#Signature: np.nonzero(a)
#Docstring:Return the indices of the elements that are non-zero.

answer(10)

(array([0, 1, 4]),)
nz = np.nonzero([1,2,0,0,4,0])
print(nz)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [22]:
matrix = np.eye(3, 3)
matrix

answer(11)

Z = np.eye(3)
print(Z)


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [31]:
array = np.random.rand(3, 3, 3)
array

#answer(12)

array([[[0.73644597, 0.8774239 , 0.54329407],
        [0.84302078, 0.16929284, 0.36437949],
        [0.23243538, 0.56921234, 0.80018114]],

       [[0.5679294 , 0.84020616, 0.68834945],
        [0.47928509, 0.00750438, 0.71163545],
        [0.37488441, 0.47370656, 0.89684234]],

       [[0.95570416, 0.69477424, 0.50047096],
        [0.39731179, 0.42943975, 0.23627085],
        [0.7228604 , 0.09309009, 0.24641607]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [35]:
array = np.random.random((10, 10))

mini = np.min(array) #array.min()
maxi = np.max(array) #array.max() 라고 해도 됨

print(mini, maxi)

answer(13)

0.10940069173617128 0.9999752231144889
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [73]:
vector = np.random.random(30)
vector.mean()

answer(14)

Z = np.random.random(30)
m = Z.mean()
print(m)


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [77]:
array = np.ones((5, 5))
array[1:4, 1:4] = 0 #array[1:-1, 1:-1] = 0
array

answer(15)

Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [81]:
array = np.ones((5, 5))

#padding하는거잖아 그니까 Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
np.pad(array, 1)

#answer(16)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [101]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)#inf : infinity 무한대
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)# 3*0.1 = 0.30000000000000004

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [106]:

answer(18)
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

Z = np.diag(1+np.arange(4),k=-1)
print(Z)
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [17]:
matrix = np.zeros((8, 8))
matrix[::2, 1::2] = 1
matrix[1::2,::2] = 1
matrix


array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

matrix[A::B]
 : A로 시작하는 index에서부터 B만큼의 step size를 가지고 slicing 한다.
   따라서 matrix[1::2, ::2]는
   - 행 - 1행부터 2의 step size를 가지고 slicing 한다. 
   - 열 - 0행부터 2의 step size를 가지고 slicing 한다. 

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [14]:
matrix = np.random.rand(6, 7, 8)
matrix = matrix.flatten()
matrix[100]

answer(20)

print(np.unravel_index(99,(6,7,8)))


np.unrabel_index(indices, dims, order ='C)
: 플랫 인덱스 배열을 좌표 배열의 튜플로 변환한다. 

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [21]:
matrix = np.random.randn(5, 5)
matrix

answer(22)

Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

hint: np.dtype


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [24]:
m1 = np.random.rand(5, 3)
m2 = np.random.rand(3, 2)
result = np.dot(m1, m2)
result

array([[0.10067758, 0.59251286],
       [0.25861982, 0.70550777],
       [0.14545553, 0.5759089 ],
       [0.16051082, 0.34902427],
       [0.28622824, 1.05549328]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [32]:
array = np.arange(11)
array

array[(3<array)&(array<=8)] *= -1
array

answer(25)

# Author: Evgeni Burovski

Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [37]:
print(sum(range(5),-1)) #왜 10이 되는지 잘 생각해봐야겠음

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [50]:
np.array(0) / np.array(0) ##nan
np.array(0) // np.array(0) ##0
np.array([np.nan]).astype(int).astype(float) 
#astype : array 전체의 형변환 해주는 메소드

2.0

즉,분모가 0일때
- array 나누기(/)는 불가하다 
- 그러나 정수부분만 구하는 것(//)은 가능하다

#### 29. How to round away from zero a float array ? (★☆☆)

In [55]:
Z = np.random.uniform(-10, 10, 10)
print(Z)
print(np.ceil(Z))#이건 단순 올림

#이 문제에서 원한건 절대값의 올림이니까
print(np.copysign(np.ceil(np.abs(Z)), Z))

#answer(29)

[ 1.53451498  1.64776143 -9.83255962 -2.52660819  0.56834416 -0.43513928
 -6.99188185 -7.7480305   5.37143575 -7.0640904 ]
[ 2.  2. -9. -2.  1. -0. -6. -7.  6. -7.]
[  2.   2. -10.  -3.   1.  -1.  -7.  -8.   6.  -8.]


#### 30. How to find common values between two arrays? (★☆☆)

In [58]:
array1 = np.array([1, 2, 3, 4])
array2 = np.array([2, 4, 9, 8])
print(np.intersect1d(array1, array2))

#answer(30)

[2 4]
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [63]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))
np.sqrt(-1) == np.emath.sqrt(-1)

nan
1j


/Users/jeonghyeonjeong/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.
/Users/jeonghyeonjeong/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [75]:
today = np.datetime64('today')
yesterday = today - np.timedelta64(1)
tomorrow = today + np.timedelta64(1)

print(yesterday, today, tomorrow)

#answer(33)

2020-02-12 2020-02-13 2020-02-14
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [92]:
np.arange('2016-07', '2016-08', dtype = 'datetime64[D]')
# 한자리수 쓸 때는 앞에 0 붙이기, 
# datetime64[D]라는 데이터 타입이 있다

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [106]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3

np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=B)

#A = np.array([1, 1, 1])하면 안되고, 
#A = np.ones([3])*1 하면 된다. 

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [118]:
random_array = np.random.uniform(1, 100,(1, 10))

print(random_array.astype(int))
print(np.ceil(random_array)-1)
print(random_array - (random_array%1))
print(np.floor(random_array)) #np.floor(a) : 각 원소 값보다 작거나 같은 가장 큰 정수 값 (바닥 값)으로 내림
print(np.trunc(random_array))#np.trunc(a) : 각 원소의 소수점 부분은 잘라버리고 정수값만 남김


#answer(36)

[[95 69 70 25 96 85  4 67 85 43]]
[[95. 69. 70. 25. 96. 85.  4. 67. 85. 43.]]
[[95. 69. 70. 25. 96. 85.  4. 67. 85. 43.]]
[[95. 69. 70. 25. 96. 85.  4. 67. 85. 43.]]
[[95. 69. 70. 25. 96. 85.  4. 67. 85. 43.]]
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [123]:
Z = np.zeros((5, 5))
Z += np.arange(5)
print(Z)

#answer(37)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [152]:
    
Z = []

def generate():
    for x in range(10):
        #print(x)
        Z.append(x)

generate()
print(Z)



[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [144]:
#answer(38)

def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)


**39.Create a vector of size 10 with values ranging from 0 to 1, both excluded**

시작점과 끝점을 균일 간격으로 나눈 점들을 생성해주는 linspace()함수도 있다.


c = np.linspace(0, 1, 6)   # start, end, num-points 

c
>array([ 0. , 0.2, 0.4, 0.6, 0.8, 1. ])

d = np.linspace(0, 1, 5, endpoint=False)

d
>array([ 0. , 0.2, 0.4, 0.6, 0.8])


출처: https://studymake.tistory.com/425 [스터디메이크]

In [163]:
Z = np.linspace(0, 1, 11, endpoint = False)[1:]
Z
#endpoint=False는 1을 없애기 위한 것, [1:]은 맨 처음의 0을 없애기 위한 것

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [164]:
#answer(39)

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [168]:
Z = np.random.random(10)
Z.sort()
Z

#answer(40)

array([0.06995419, 0.24038285, 0.2734405 , 0.30348367, 0.37260927,
       0.4738386 , 0.5530549 , 0.56110578, 0.6190644 , 0.86466815])

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)